name: Build workflow
on: 
  push:
    branches:
      - main

jobs:
  unittest:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3

      - name: Setup .Net Core SDK
        uses: action/setup-dotnet@v2
        with:
          dotnet-version: 3.1
      - name: Install dependencies
        run: dotnet restore
      - name: Build 
        run: dotnet build --configuration Release --no-restore
      - name: Test 
        run: dotnet test --no-restore --verbosity normal
