name: Dependencies Review (Allow Licenses)
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    name: Dependencies Review
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dependencies Review
        uses: actions/dependency-review-action@v2 
        with:
          fail-on-severity: critical
          allow-licenses: MIT
